# https://github.com/deepestsleep/assignment 101165940
language: node_js

node_js:
  - "10.9.0"

cache: npm

before_install:
  - ls -la
  - mkdir dist
  - cd dist
  - ls
  -ls -la

install:
  -npm install

script:
  -npm run build
  -npm run test
